language: generic 
sudo: required #Hey travis we need super user level permissions
services:    #telling travis we need docker cli preinstalled. Travis install docker cli in the container
  - docker

before_install:
  - docker build -t georgiborisov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true georgiborisov/docker-react npm run test

deploy: #For AWS
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-881957626157"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY